phosphorus: 
  characteristicName: 'Phosphorus'

nitrogen: 
  characteristicName: 'Nitrogen'

temperature: 
  characteristicName: ["Temperature, sample", "Temperature, water","Temperature"]

arsenic: 
  characteristicName: 'Arsenic'

chlorophyll:  
  characteristicName: ["Chlorophyll", "Chlorophyll A", "Chlorophyll a","Chlorophyll a (probe relative fluorescence)","Chlorophyll a (probe)","Chlorophyll a - Periphyton (attached)", "Chlorophyll a - Phytoplankton (suspended)", "Chlorophyll a, corrected for pheophytin", "Chlorophyll a, free of pheophytin", "Chlorophyll a, uncorrected for pheophytin", "Chlorophyll b", "Chlorophyll c", "Chlorophyll/Pheophytin ratio"]
  
doc:  
  characteristicName: ["Organic carbon", "Total Particulate Organic Carbon"]

secchi:
  characteristicName: ["Depth, Secchi disk depth", "Depth, Secchi disk depth (choice list)", "Secchi Reading Condition (choice list)", "Secchi depth", "Water transparency, Secchi disc"]
  
lakes: 
  siteType: "Lake, Reservoir, Impoundment"
  
all: null

